### PR TITLE
Decrypt and format mail content flow

### PR DESCRIPTION
**Pull request by Swiip**
*EDIT:* Fully rewritten

- [x] Organized code in `src/app/hooks`, `src/app/helpers`, `src/app/models` (TS interfaces), `src/app/components/messages`. Perhaps some of these should go in `react-components` and `proton-shared` but easier to keep in a single repo for now.
- [x] Centralized message processing in `useComputeMessage`.
- [x] Defined a `MessageExtended` type to deal with all messages computation without mutating the original `Message` from the server
- [x] Body decryption in `useDecryptMessage` defined as a message computation
- [x] Reuse and adapt Angular code for body transformations in `helpers/transforms` and attachment processings in `helpers/attachments` and `helpers/embedded`
- [x] Implement "Show remote images" and "Show embedded images"
- [x] Implement attachments footer and download
- [x] Auto expand and scroll to last mail of a conversation
- [x] Improvements on using the design system, especially in the recipients section
- [x] New rendering of dates using `date-fns`
- [x] Lock component showing encryption status
- [x] Started to switch progressively to TS

Known left to do:
- Deal with cache, especially for message computing and attachments
- Deal with encryption signatures
- Deal with mime messages
- Lots of `Extra` message of the message header to implement

Manager: @matstaz 
Test server:

### CODE REVIEW

**Comment by DeepSpaceHarbor** [comment]
**Summary**
Clicking on the bottom of the message header, closes the message.

**Steps to reproduce**
1. Open message
2. Click on the bottom of the message header. 
Ex: image

**Expected behavior**
Same as current beta, nothing should happen.

**Current behavior**
The message is closed.

**Comment by DeepSpaceHarbor** [comment]
**Summary**
When message is closed & opened for the second time, the images are loaded automatically.
This doesn't happen in v3/v4 beta.
imho, the new behavior is better, but I'm not sure if this change has any security implications.

**Steps to reproduce**
1. Open the message `(2)Test with images`
2. Click load and open the embedded and remote images
3. Click on the message header, to close the message.
4. Click on the header, to open the message from step 4.

**Expected behavior**
In the current version(v3/v4 beta), the image load permissions has to be approved each time the message is opened.

**Current behavior**
When opening the message for the second time, the images are automatically loaded.

**Comment by DeepSpaceHarbor** [comment]
**Summary**
Not sure if it's in the scope of this pr, but the message view is not responsive.

**Screenshot**
image

**Comment by Swiip** [comment]
- clicking on the bottom of the message: to fix
- images the second time: good question, @matstaz ?
- responsiveness: definitely a new issue, I created https://github.com/ProtonMail/proton-mail/issues/25 but could be an other one

**Comment by Swiip** [comment]
Clicking on the bottom of the message fixed on https://tartiflette.protonmail.blue/login

**Comment by matstaz** [comment]
@Swiip regarding reloading images, I think it is ok to not have to reload them. If the message has been decrypted and the user already requested to load the content/imasges, I don't see a reason why we should not do it automatically as long as the user stays in the same email thread.

@EpokK thoughts? Is there a security threat with this approach?

**Comment by EpokK** [comment]
> @EpokK thoughts? Is there a security threat with this approach?

I'm OK with this approach, you can save the state locally.

**Comment by Swiip** [comment]
Notes after the review meeting:

- Test all kinds of message content. Especially a complicated kind mime message where everything including subject is encrypted. (https://github.com/ProtonMail/proton-mail/issues/24)
- Check for properties labels and labelsID in Message and Conversion. labelIDs should not be used in Message anymore.
- Add conversationID to the type Message. It only exists for message type. Could be a good check to distinguish Message and Conversation
- Move mark as read action after decrypt (to not mark as read a message which could not be decrypted
- The embedded logic has to be refactored at one point (issue to create)
- Extras of the header have to be under the action buttons
- The message cache should start with 50 message capacity for a start. (for https://github.com/ProtonMail/proton-mail/pull/19)
- Test the message cache behavior when the conversation is bigger than the cache size. (for https://github.com/ProtonMail/proton-mail/pull/19)
- We could considere pre load some mail in advance. (issue to create)
- Add an action allowing to open all message from a conversation (issue to create)
- Implement infinite scroll. For conversation list (at left). But why not also for message list (at right) (issue to create)
- Implement encryption signature logic (issue to create)

**Pull request merged**
